name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Or whichever branches you want to trigger on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build \
          --file Dockerfile \
          --tag johnvinhac/ai-service:latest \
          .

      # Step 4: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push johnvinhac/ai-service:latest
